version: "3"
services:
  app:
    image: nginx
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - 3001:80

  imaginary:
    image: h2non/imaginary:latest
    environment:
       PORT: 9000
    command: -enable-url-source -http-cache-ttl=1000
    ports:
      - "9000:9000"